### PR TITLE
Added ability to access properties of arrays

### PR DESCRIPTION
**Pull request by jonahbron**
Queries to access the length of an array, or items at a specific index are not currently possible.  This simple change gives queries the ability to access array properties if the property exists.

### CODE REVIEW

**Comment by jonahbron** [comment]
Note however, that this can break certain queries that worked properly before.  For example:

```
{
    "array": [
        {
            "length": 10
        },
        {
            "length": 9
        }
    ]
}
```

Accessing both of those `length` properties is no-longer possible.  Perhaps a change to the syntax is necessary to remove that ambiguity?

**Comment by hakovala** [comment]
I haven't touched this project in few years, after I created it. lol
It was a nice little teaching project for myself, but I not maintaining this anymore.
I don't even have any idea how this even works or how to use Grunt.

I merged your changes and pushed new version to npm, but this is going to be last update from
me.

**Comment by jonahbron** [comment]
No problem, thank you Harri.  Would you be willing to give me permission to push updates to NPM?  We're using this in one of our core components, and it wouldn't surprise me if we needed to make further improvements.  That could be good for everyone, especially considering how popular your package is.

**Comment by hakovala** [comment]
Sure, i can give you npm permissions.
Nice that somebody finds it useful. I didn't even notice that somebody used this module. lol

Now I just need to figure out how to give you correct permissions..

**Comment by hakovala** [comment]
Okkey.. Now you are added as a collaborator to this project, both in npm and in github.
Hopefully everything works correctly. :)

**Comment by jonahbron** [comment]
Great, thanks very much.

**Pull request merged**
